build:
  environment:
    php:
      version: 7.0.24 # Common versions: 5.4, 5.5, 5.6, 7.0 or hhvm
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=build/logs/clover.xml ./tests'
        coverage:
          file: 'build/logs/clover.xml'
          format: 'php-clover'
checks:
  php:
    custom_coding_standard:
      ruleset_path: 'phpcs.xml'
