language: php

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

group: deprecated-2017Q3

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
 - composer self-update
 - composer install --no-interaction

before_script:
  - composer install --dev
  - composer self-update
  - mkdir -p build/logs

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml ./tests
  - vendor/bin/phpcs --runtime-set ignore_warnings_on_exit 1 --standard=phpcs.xml src
